### ISSUE TITLE
Can't we make a demo website using this library? like water.css demo documentation

### ISSUE THREAD

**Issue by doniwirawan** [valclassdevelop/valclassDocumentation#5]
[https://watercss.kognise.dev/](https://watercss.kognise.dev/)

**Comment by khoirulhudaa** [comment]
Kenapa saya tidak bisa akses link yg anda berikan?

Pada tanggal Kam, 9 Sep 2021 19.46, Doni Wirawan ***@***.***>
menulis:

**Comment by doniwirawan** [comment]
of course you can or just copy it

**Comment by khoirulhudaa** [comment]
hello mas doniirawan, bisa kasih saya contoh penggunaan water.css nya?

**Comment by doniwirawan** [comment]
maksud saya yuk kita buat library anda seperti itu, kita buat docsnya sama
seperti demikian

Pada tanggal Sel, 28 Sep 2021 pukul 14.46 Muhammad Khoirul Huda <
***@***.***> menulis:

**Comment by khoirulhudaa** [comment]
Boleh kita chat via WhatsApp saja? Biar lebih akrab dan leluasa diskusi nya
kwkwk

Pada tanggal Rab, 29 Sep 2021 07.54, Doni Wirawan ***@***.***>
menulis:
