### ISSUE TITLE
Documentation page, can't hover emoji card, on v-emoji page

### ISSUE THREAD

**Issue by MyFRA** [valclassdevelop/valclassDocumentation#6]
When I check emoji lists, on v-emoji page. I want to copy them, But when I hover on emoji that I want, but my cursor is over another emoji 

![Screenshot_2021-10-13_12-07-55](https://user-images.githubusercontent.com/60420319/137070898-caff67ad-5589-496d-ae63-6bbb51b27223.png)

**Comment by khoirulhudaa** [comment]
ok tom makasih banget udah share issue di valclass, tunggu invit saya, hehe
